# Generated by Django 5.1.3 on 2024-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('Taxi', 'Taxi'), ('Bike', 'Bike'), ('Auto', 'Auto'), ('Car', 'Car')], max_length=5)),
                ('date_time', models.DateTimeField()),
                ('seats_available', models.IntegerField()),
                ('cost_per_seat', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
