# Generated by Django 5.1.3 on 2024-11-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_user_alter_ride_cost_per_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='seats_available',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
    ]
